// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPxPCGE5TYgodNovfZ7w1r0PzSsbm8Pp8',
    appId: '1:176271187302:web:08e659231b10b79cec3ca7',
    messagingSenderId: '176271187302',
    projectId: 'penny-89979',
    authDomain: 'penny-89979.firebaseapp.com',
    storageBucket: 'penny-89979.appspot.com',
    measurementId: 'G-E4T8MBRGD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXJ-hIgbjSqUkYOMUrRr6wblzIhl79ps',
    appId: '1:176271187302:android:f6f27df3ff4dfab9ec3ca7',
    messagingSenderId: '176271187302',
    projectId: 'penny-89979',
    storageBucket: 'penny-89979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLKGCkjwPqJbyNu047v1Sqmj3ofDoaqg',
    appId: '1:176271187302:ios:e0bc03937f805df4ec3ca7',
    messagingSenderId: '176271187302',
    projectId: 'penny-89979',
    storageBucket: 'penny-89979.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLKGCkjwPqJbyNu047v1Sqmj3ofDoaqg',
    appId: '1:176271187302:ios:e0bc03937f805df4ec3ca7',
    messagingSenderId: '176271187302',
    projectId: 'penny-89979',
    storageBucket: 'penny-89979.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPxPCGE5TYgodNovfZ7w1r0PzSsbm8Pp8',
    appId: '1:176271187302:web:e5ed2ad03aba3198ec3ca7',
    messagingSenderId: '176271187302',
    projectId: 'penny-89979',
    authDomain: 'penny-89979.firebaseapp.com',
    storageBucket: 'penny-89979.appspot.com',
    measurementId: 'G-WRLH4CJRZC',
  );
}
